[general]
blur = true
theme = "macchiato"

[keybinds]
poweroff = "systemctl poweroff"
reboot = "systemctl reboot"
suspend = "systemctl suspend"
hibernate = "systemctl hibernate"
logout = "hyprctl dispatch exit"
